[package]
name = "perfcnt"
version = "0.3.0"
authors = ["Gerd Zellweger <mail@gerdzellweger.com>"]
description = "Library to configure and read hardware performance counters in rust."
homepage = "https://github.com/gz/rust-perfcnt"
repository = "https://github.com/gz/rust-perfcnt"
documentation = "http://gz.github.io/rust-perfcnt/perfcnt/"
readme = "README.md"
keywords = ["performance", "counter", "events", "pmu", "perf"]
license = "MIT"

[dependencies]
bitflags = "0.7.*"
libc = "0.1.10"
x86 = {git = 'https://github.com/dzobbe/rust-x86.git'}
mmap = "0.1.*"
byteorder = "0.5"
nom = "^1.2.4"

[[bin]]
name = "perfcnt-list"
path = "src/bin/list.rs"


[[bin]]
name = "perfcnt-parse"
path = "src/bin/parse.rs"
